# Site settings
title: matmangio
name: Matteo Mangioni
email: mat.mangioni@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Matteo Mangioni's gamedev portfolio and blog about games!
url: "https://matmangio.it"
repository: "matmangio/matmangio.github.io"
github_username: matmangio

# Build settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark
title_separator: "|"
date_format: "%Y-%m-%d"
enable_copy_code_button: true
search: false
locale: "en"
markdown: kramdown

head_scripts:
footer_scripts:

og_image: /assets/images/logo.png
og_image_alt: "Site logo"
teaser: /assets/images/logo.png
masthead_title: ""

show_taxonomy: false

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/preview

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Matteo Mangioni"
  avatar : "/assets/images/logo.png"
  bio    : "Game Designer and Developer. Proud member of <b><a href='https://wauhaus.itch.io/'>Wauhaus Productions</a></b>!"
  location: "Milan, Italy"
  links:
    - label: "Itch.io"
      icon: "fa-brands fa-itch-io"
      url: "https://matmangio.itch.io/"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/matteo-mangioni-18302224b/"
    - label: "Email"
      icon: "fa-solid fa-at"
      url: "mailto:mat.mangioni@gmail.com"
    - label: "Feed"
      icon: "fa-solid fa-square-rss"
      url: "https://matmangio.it/feed.xml"

footer:
  links:
    - label: "Itch.io"
      icon: "fa-brands fa-itch-io"
      url: "https://matmangio.itch.io/"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/matteo-mangioni-18302224b/"
    - label: "Email"
      icon: "fa-solid fa-at"
      url: "mailto:mat.mangioni@gmail.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      show_date: true
      update_date: false
      toc: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

collections:
  games:
    output: true
    permalink: /:collection/:path/

feed:
  disable_in_development: true
